"""Carry out a :class:`~distrokit.gpu.plan.GpuPlan` on a system root."""

from __future__ import annotations

import json
import time
from pathlib import Path

from .. import boot, pkg, util
from ..branding import Branding, load as load_branding
from .plan import GpuPlan


def config_files(plan: GpuPlan, branding: Branding) -> dict[str, str | None]:
    """Files the plan writes, as {absolute path: content}; None means delete."""
    bid = branding.id
    header = f"# Generated by `{branding.cli} gpu configure`. Changes are overwritten;\n# put your own settings in a separate file.\n"
    files: dict[str, str | None] = {}

    files[f"/etc/modprobe.d/{bid}-gpu.conf"] = (header + "\n".join(plan.modprobe) + "\n") if plan.modprobe else None

    mk = []
    if plan.initramfs_modules:
        mk.append("MODULES+=(" + " ".join(plan.initramfs_modules) + ")")
    if plan.drop_kms_hook:
        mk.append("# Keep nouveau out of the initramfs; the NVIDIA modules above provide early KMS.")
        mk.append("HOOKS=(${HOOKS[@]/kms})")
    files[f"/etc/mkinitcpio.conf.d/20-{bid}-gpu.conf"] = (header + "\n".join(mk) + "\n") if mk else None

    files[f"/etc/udev/rules.d/80-{bid}-gpu.rules"] = (header + plan.udev_rules) if plan.udev_rules else None

    env_lines = "".join(f"{k}={v}\n" for k, v in sorted(plan.env.items()))
    files[f"/etc/{bid}/gpu.env"] = header + env_lines
    files[f"/etc/environment.d/90-{bid}-gpu.conf"] = (header + env_lines) if plan.env else None
    return files


def write_files(plan: GpuPlan, root: Path, branding: Branding, runner: util.Runner) -> list[str]:
    changed = []
    for path, content in config_files(plan, branding).items():
        target = root / path.lstrip("/")
        if content is None:
            if target.exists():
                runner._emit(f"remove {path}")
                if not runner.dry_run:
                    target.unlink()
                changed.append(path)
            continue
        current = util.read_text(target, None) if target.exists() else None
        if current != content:
            runner._emit(f"write {path}")
            if not runner.dry_run:
                util.atomic_write(target, content)
            changed.append(path)
    boot_changed = plan.kernel_params != _current_fragment(root, branding)
    if boot_changed:
        runner._emit(f"kernel parameters: {' '.join(plan.kernel_params) or '(none)'}")
        if not runner.dry_run:
            boot.set_fragment("20-gpu", plan.kernel_params, root, branding, "GPU driver parameters")
        changed.append("kernel command line")
    return changed


def _current_fragment(root: Path, branding: Branding) -> list[str]:
    path = boot.cmdline_dir(root, branding) / "20-gpu.conf"
    if not path.is_file():
        return []
    params: list[str] = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            params.extend(line.split())
    return params


def apply(
    plan: GpuPlan,
    *,
    root: Path | str = "/",
    runner: util.Runner | None = None,
    branding: Branding | None = None,
    install_packages: bool = True,
    remove_conflicts: bool = True,
    user: str | None = None,
    regenerate: bool = True,
) -> dict:
    root = Path(root)
    runner = runner or util.Runner()
    branding = branding or load_branding()
    result: dict = {"installed": [], "removed": [], "aur_built": [], "files": [], "services": []}

    if install_packages:
        repo = plan.packages + plan.compute_packages
        result["aur_built"] = pkg.install_with_fallback(repo, plan.aur_packages, runner, root, user)
        result["installed"] = plan.all_packages
    if remove_conflicts and plan.conflicts:
        result["removed"] = pkg.remove(plan.conflicts, runner, root)

    result["files"] = write_files(plan, root, branding, runner)

    for unit in plan.services:
        # Only enable units that exist (e.g. nvidia-powerd ships with nvidia-utils).
        unit_path = root / "usr" / "lib" / "systemd" / "system" / unit
        if runner.dry_run or unit_path.exists():
            boot.in_root(runner, root, ["systemctl", "enable", unit])
            result["services"].append(unit)

    if regenerate and (result["files"] or result["installed"] or result["removed"]):
        boot.in_root(runner, root, ["mkinitcpio", "-P"])
        if not runner.dry_run:
            runner._emit(boot.update(root, runner, branding))

    state = {
        "configured_at": int(time.time()),
        "plan": plan.to_dict(),
    }
    if not runner.dry_run:
        util.write_json(branding.system_paths(root).gpu_state, state)
    return result


def load_state(root: Path | str = "/", branding: Branding | None = None) -> dict | None:
    branding = branding or load_branding()
    return util.read_json(branding.system_paths(root).gpu_state)


def dumps(plan: GpuPlan) -> str:
    return json.dumps(plan.to_dict(), indent=2)
